Hello World in Python
elasComputacao/BabySteps pull request #37
Opened 2020-10-06 19:05 UTC by anajuliazhu

2020-10-06 20:26 UTC, beatrizadm commented
Boa tarde!! ficamos muito felizes com a sua PR, mas no momento como temos issues abertas, não estamos aceitando helloword em linguagens já existentes no repositório. Você gostaria de contribuir com a Galeria ou com as Frases?

2020-10-07 13:22 UTC, beatrizadm requested changes
Bom dia!! ficamos muito felizes com a sua PR, mas no momento como temos issues abertas, não estamos aceitando helloword em linguagens já existentes no repositório. Você gostaria de contribuir com a Galeria ou com as Frases?

2020-10-09 19:07 UTC, anajuliazhu commented
Olá, boa tarde!! Desculpa a demora para responder, a semana foi super corrida e só consegui visualizar agora. Enfim, gostaria de contribuir com a Galeria sim, enquanto as Frases eu já contribui, poderei contribuir novamente?

2020-10-11 14:09 UTC, beatrizadm commented
Pode contribuir novamente sim!! Qualquer dúvida é só perguntar :)

2020-10-23 15:14 UTC, closed without merging