Update frases.md
elasComputacao/BabySteps pull request #69
Opened 2020-10-30 19:27 UTC by anajuliazhu

2020-10-30 20:37 UTC, beatrizadm commented
Boa noite Ana, acho que você apagou sua frase sem querer, quando puder manda ela novamente :)

2020-10-30 21:13 UTC, beatrizadm requested changes

2020-10-30 21:13 UTC, beatrizadm commented on Frases.md
> +
Boa noite Ana, acho que você apagou sua frase sem querer, quando puder manda ela novamente :)

2020-11-01 17:51 UTC, anajuliazhu commented on Frases.md
> +
Boa tarde Beatriz! Realmente eu tinha apagado kkkkk, desculpa. Mas já consertei, confere se deu certo agora :)

2020-11-01 20:24 UTC, merged